services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - jeffaug-network

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./:/var/www/html
    networks:
      - jeffaug-network
    build:
      context: .
      dockerfile: php.Dockerfile

  vite:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - jeffaug-network

networks:
  jeffaug-network:
    driver: bridge
